### ISSUE TITLE
Bengali Translation Progress

### ISSUE THREAD

**Issue by tesseralis** [reactjs/bn.reactjs.org#1]
## Maintainer List

* @nutboltu
* @shakib609 

## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the [glossary](https://github.com/reactjs/bn.reactjs.org/wiki/Glossary) and style guide (once they exist) to understand how to translate various technical and React-specific terms.

Please be prompt with your translations! If you find that you can't commit anymore, let the maintainers know so they can assign the page to someone else.

# Work List

(🏃 Work in Progress; 👀 In Review)

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

* [ ] Home Page (@tesseralis) #1

When PRs are merged, make sure to mark that page as completed!

## Slack Channel
If you get stuck and need help, please join our slack channel [click here](https://rt-slack-invite.herokuapp.com/) to join and ask any question in #bn channel

## Guidelines
Please follow the wiki page https://github.com/reactjs/bn.reactjs.org/wiki

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

* [x] Home Page (@nutboltu) #4 #10 
* [ ] Tutorial  #8 #15  (Partially translated) (@tamzidkarim , @oxfordhalfblood )

### Basics

* [x] Hello World (@sazzadsazib) #9 
* [x] Introducing JSX (@shakib609) #60
* [x] Rendering Elements (@tamzidkarim) #77
* [x] Components and Props (@nutboltu) #76 
* [x]  State and Lifecycle(@shakib609) #13 
* [x] Handling Events (@shakib609) #19
* [x] Conditional Rendering(@nutboltu ) #26 
* [x] Lists and Keys(@ImranMH) #14
* [ ] Forms(@Twaha-Rahman) #18
* [x] Lifting State Up (@shakib609) #24
* [x] Composition vs Inheritance (@shakib609) #28 
* [x] Thinking in React  #46 (@JubayerJoy)

### API Reference

* [ ] React (@ShahadIshraq)
* [ ] React.Component (@soumiDeb)
* [ ] ReactDOM
* [ ] ReactDOMServer
* [x] DOM Elements (@nutboltu) #39 
* [x] SyntheticEvent (@nutboltu) #53
* [x] Test Utilities (@shakib609) #42
* [x] Shallow Renderer (@Twaha-Rahman) #16
* [x] Test Renderer (@shakib609) #45
* [x] JS Environment Requirements (@shakib609) #20
* [ ] Glossary

### Navigation

These are the navigation links that appear in the sidebar. Possibly wait until
the corresponding sections are translated to do these.

* [ ] tutorial/nav.yml
* [ ] docs/nav.yml

## Next Steps

These are the next most important translations, ordered by importance:

### Installation

* [x] Getting Started(@jamal-pb95) #25
* [x] Add React to a Website(@jamal-pb95) #62
* [x] Create a New React App (@fmabid) #34 
* [x] CDN Links (@fmabid ) #36 

### Hooks

Everyone is hooked on hooks! People are really excited for these and it would be great for them to be translated.

  * [ ] 🏃Introducing Hooks (@uraniumreza)
  * [ ] Hooks at a Glance (@rummanhasnayeen)
  * [ ] Using the State Hook (@sabbir073)
  * [ ] Using the Effect Hook (@sabbirshawon)
  * [x] Rules of Hooks (@shakib609) #41
  * [ ] Building Your Own Hooks (@SourangshuGhosh)
  * [ ] Hooks API Reference
  * [ ] Hooks FAQ

### Warnings

These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
 
* [ ] dont-call-proptypes
* [ ] invalid-aria-prop
* [ ] invalid-hook-call-warning
* [ ] legacy-factories
* [ ] refs-must-have-owner
* [ ] special-props
* [ ] unknown-prop

### Advanced Guides

* [ ] Accessibility
* [ ] Code-Splitting
* [ ] Context
* [ ] Error Boundaries (@shakib609)
* [ ] Forwarding Refs
* [x] Fragments (@shakib609) #54
* [ ] Higher-Order Components
* [ ] Integrating with Other Libraries
* [ ] JSX In Depth
* [ ] Optimizing Performance
* [x] Portals (@nutboltu) #63
* [ ] React Without ES6
* [x] React Without JSX (@shakib609) #55
* [ ] Reconciliation
* [ ] Refs and the DOM
* [ ] Render Props
* [ ] Static Type Checking
* [ ] Strict Mode
* [x] Typechecking With PropTypes (@lastsaintcrucified) #69
* [ ]  🏃 Uncontrolled Components (@lastsaintcrucified)
* [x] Web Components (@shakib609) #56

### FAQ

* [x] APIs and AJAX (@Twaha-Rahman) #22
* [x] Babel, JSX, and Build Steps (@Twaha-Rahman) #17 
* [ ] Passing Functions to Components
* [ ] Component State
* [x] Styling and CSS (@Twaha-Rahman) #23
* [ ] File Structure
* [ ] Versioning Policy
* [ ] Virtual DOM and Internals (@Twaha-Rahman)

### Contributing

Priority: Low

* [ ] How to Contribute
* [ ] Codebase Overview
* [ ] Implementation Notes
* [ ] Design Principles

### Components

Components in `src/components` that have some text in them.

* [ ] CodeEditor
* [ ] CodeExample
* [ ] ErrorDecoder
* [ ] LayoutFooter
* [ ] LayoutHeader
* [ ] MarkdownPage

## Additional Translations

These are not the primary translation targets.

* [ ] Blog
* [ ] Community

**Comment by tesseralis** [comment]
@nutboltu, @zahidulmcc please keep this issue updated to track your progress! Please let me know if you need any help getting this translation started. You can also join the slack channel here: rt-slack-invite.herokuapp.com

**Comment by nutboltu** [comment]
@tesseralis We already joined the slack and opened a channel where we will discuss  abou our progress.

**Comment by nutboltu** [comment]
I started working on Core Pages (Home Page)

**Comment by sazzadsazib** [comment]
Hello, I am interested in translating  "Hello World" page from the list.. later on I will add few more page if I get chance..

**Comment by ImranMH** [comment]
I am also interested to involve in this translation process. Let me know how much already done

**Comment by nutboltu** [comment]
@sazzadsazib and @ImranMH could you tell us more about your translation or open source background?
So that @tesseralis can approve you guys as maintainers

**Comment by sazzadsazib** [comment]
> @sazzadsazib and @ImranMH Please follow this [instruction](https://github.com/reactjs/reactjs.org-translation#adding-a-maintainer) to add yourself in the maintainer list.
> Or you guys can tell a brief about your translation or open source background. If @tesseralis approves, I will add you as maintainers.

Hello, I've done open source contribution such as [arunghosh/react-heatmap-grid](https://github.com/arunghosh/react-heatmap-grid) . [Ness.css](https://github.com/nostalgic-css/NES.css) and also have few [NPM packages](https://www.npmjs.com/~sazzadsazib). I am serious about open source contribution and as Bengali I want to help to translate react in Bangla. I translated parital [hello-world.md](https://github.com/sazzadsazib/bn.reactjs.org/blob/master/content/docs/hello-world.md) here.. if you think I can help react community to translate in Bangla I will contribute.

Thanks

**Comment by zpbappi** [comment]
Hi @nutboltu and @zahidulmcc, I would like to contribute to this effort. My quality as a translator is- I am a native Bangla speaker 😄 . Other than that, I have working experience with React, have a somewhat good understanding of Javascript and contributing to opensource projects on a regular basis. I hope to provide a helping hand.

**Comment by nutboltu** [comment]
@sazzadsazib , @zpbappi  I added you guys in this PR https://github.com/reactjs/reactjs.org-translation/pull/61
@ImranMH  Can you please add your background in the PR comment.

@tesseralis Please review this PR

**Comment by zpbappi** [comment]
Since @sazzadsazib has already started and partially completed the Hello World, I have taken the next item on the list and updated the list accordingly.

**Comment by shakib609** [comment]
I'll start translating the **API Reference > ReactDOM** page.
Hopefully, I can do my part to translate **React.js Documentation** to Bengali. :smile:

**Comment by tanvirraj** [comment]
@tesseralis and @nutboltu 
i want translate  **`Rendering Elements`** page

**Comment by nutboltu** [comment]
@tanvirraj Please go ahead :)

**Comment by shakib609** [comment]
I will start translating **Basics > State and Lifecycle**. :octocat:
Assign it to me kindly.

**Comment by ImranMH** [comment]
I already completed lists and keys page . Just final check before make a PR

**Comment by rajiveislam** [comment]
I would like to start with conditional rendering.

**Comment by jamal-pb95** [comment]
Hi @nutboltu, @tesseralis, and @zahidulmcc, I would like to contribute to this project. I am a native Bengali speaker 😄 . Other than that, I have working experience with React, have a somewhat good understanding of Javascript and contributing to opensource projects.

**Comment by jamal-pb95** [comment]
I would like to go with **Installation>Getting Started** page

**Comment by shakib609** [comment]
I will start translating **Basics > Handling Events**. :octocat:
Assign it to me kindly.

**Comment by Twaha-Rahman** [comment]
I am starting to translate **API Reference** > **Shallow Renderer**. can anyone kindly assign it to me.

**Comment by Twaha-Rahman** [comment]
I am starting to translate **API Reference** > **Babel, JSX, and Build Steps**. Can anyone kindly assign it to me.

**Comment by shakib609** [comment]
I will start translating **API Reference > JS Environment Requirements**. :octocat:
Assign it to me kindly.

And @nutboltu vai, I would like to become a maintainer of this project. I have a good understanding of **React** and **Javascript** and also I have contributed to this project and plan to keep contributing. I have also contributed to many open-source projects. You can find a list of them [here](https://ghuser.io/shakib609).

Hopefully, I will be added. :)

**Comment by Twaha-Rahman** [comment]
I have made a pull request for the page "Babel, JSX, and Build Steps" with a translation already. Why is it still not assigned to me on the above list? Am I missing any rules? (I also noticed I got the Shallow Renderer assigned to me....so I am bit confused....) Can anybody point out what I am doing wrong?

**Comment by shakib609** [comment]
> I am starting to translate **API Reference** > **Babel, JSX, and Build Steps**. Can anyone kindly assign it to me.

Maybe you meant **FAQ > Babel, JSX, and Build Steps**?

**Comment by nutboltu** [comment]
@shakib609 I will add you as a maintainer 🥇

**Comment by Twaha-Rahman** [comment]
@shakib609  I am starting to translate **FAQ** > **APIs and AJAX**. Can anyone kindly assign it to me.

**Comment by Twaha-Rahman** [comment]
@shakib609  I am starting to translate **FAQ** > **Styling and CSS**. Can anyone kindly assign it to me.

**Comment by shakib609** [comment]
Please translate one page at a time as @nutboltu vai suggested [here](https://github.com/reactjs/bn.reactjs.org/pull/21#pullrequestreview-213363853) @Twaha-Rahman

**Comment by jamal-pb95** [comment]
Hello @nutboltu bhai, I have submitted my first translation PR **Installation>Getting Started Page**. please see and merge.

**Comment by jamal-pb95** [comment]
Please me for **Installation >  Add React to a Website** page translation

**Comment by uraniumreza** [comment]
Wanna work with `Hooks` section; starting with **Introducing Hooks**

**Comment by nutboltu** [comment]
@uraniumreza Please go ahead

**Comment by nutboltu** [comment]
@shakib609 @Twaha-Rahman , @sazzadsazib , @ImranMH , @zpbappi Let's restart the pace of the translation and finish the translation 😃

**Comment by fmabid** [comment]
**Installation**
- Create a New React App
I just started working on this page.

**Comment by nafistiham** [comment]
Hello, @nutboltu and other maintainers. I would love to contribute on the page **Thinking in React**.

To be honest, I am not an expert. I am a junior software engineer in a software firm named [DSi](http://www.dsinnovators.com) and I have worked on several web projects. But, I aim to contribute to open projects starting with translation. 

As a translator, my experiences are translating Bangla poems to English (written by my mother) for an international conference and working on my Bangla book that is going to be published by [Prothoma](https://www.prothoma.com). It is a collection of translated Olympiad problems and solutions.

I hope I'll be let contributing to this project.

**Comment by nutboltu** [comment]
@nafistiham Please go ahead. I added you to `Thinking in React.` page.

**Comment by nafistiham** [comment]
I have PRed for the `Thinking in React` page. Now, I am working on the `Components and Props` page. Please review my PR and let me know if anything needs to be changed over.

**Comment by nafistiham** [comment]
Just completed the `Components and Props` page and now working on the `React` page in the API reference.

I have edited each line individually to maintain the addition and deletion ratio this time https://github.com/reactjs/bn.reactjs.org/pull/46/commits/54d3f9302c8a92b1f830ead051267d2f2f2f8c81

**Comment by rummanhasnayeen** [comment]
Being a native Bengali speaker and react developer, I would like to contribute on the **Hooks at a Glance** page. It would be great if you could assign this page against my username.

**Comment by nutboltu** [comment]
@rummanhasnayeen Thanks for your interest. Please go ahead.

**Comment by nafistiham** [comment]
I finished and committed the React API page. The references have been a little tricky to translate. I will be waiting for the reviewers to resolve my mistakes and merge the files.
In the meantime, I will be working on `React.Component` API page.

**Comment by sabbir073** [comment]
I will start Very soon. It will be my pleasure if any maintainer can mention me a page to translate.

**Comment by shakib609** [comment]
> I will start Very soon. It will be my pleasure if any maintainer can mention me a page to translate.

@sabbir073 You can start with the `API Reference > React.Component` page.

**Comment by sabbir073** [comment]
> > I will start Very soon. It will be my pleasure if any maintainer can mention me a page to translate.
> 
> @sabbir073 You can start with the `Using the State Hook` page.

Sure, i started it.

**Comment by ShahadIshraq** [comment]
Hello, want to start with `React.Component` from  `API Reference` section

**Comment by shakib609** [comment]
> Hello, want to start with `React.Component` from `API Reference` section

Hello, @ShahadIshraq. Sorry for the inconvenience. We forgot to assign the `React.Component` page to the previous translator. There's already a PR(#48) for that page. You can start translating the `React` page instead. Shall I assign it to you?

Again really sorry for the inconvenience.

**Comment by ShahadIshraq** [comment]
> > Hello, want to start with `React.Component` from `API Reference` section
> 
> Hello, @ShahadIshraq. Sorry for the inconvenience. We forgot to assign the `React.Component` page to the previous translator. There's already a PR(#48) for that page. You can start translating the `React` page instead. Shall I assign it to you?
> 
> Again really sorry for the inconvenience.

No problem. Please assign the `React` page to me

**Comment by nutboltu** [comment]
@ShahadIshraq  I added you to the `React` page. 👍

**Comment by nutboltu** [comment]
**Announcement**

As we are planning to **accelerate** our translation process and to get the core pages done, we should prioritise those pages to finish first.

@zpbappi , @tanvirraj  and @nafistiham if you guys aren't working on the core pages, can you please remove yourselves only from the core pages so that others can pick them up.

If we don't get any response from you guys, we assume you guys aren't working on those pages and assign those pages to other.

Thanks 🇧🇩

**Comment by zpbappi** [comment]
@nutboltu sorry for the delay, not getting enough time. I have removed my name from the task. Hopefully, someone will pick it up.

**Comment by nutboltu** [comment]
@zpbappi no worries. you can pick any other pages it you want. thanks for you quick reply 😄

**Comment by nafistiham** [comment]
Apologies for such inconvenience. Please do remove me from react.component which is open in [this PR](https://github.com/reactjs/bn.reactjs.org/pull/48)
But, I have tried doing some contribution in [this PR](https://github.com/reactjs/bn.reactjs.org/pull/46) which I was told to close. Please have a look at it. These works haven't been confirmed/merged or corrected yet. I'd defnitely like to help correcting them if needed.

**Comment by shakib609** [comment]
Thanks for replying @nafistiham. I am removing you from these pages for now. On the other hand, you can try correcting your PRs according to the ways @nutboltu vai and I suggested. If you are having problems creating separate PRs for each files. I can help you out.

**Comment by sabbirshawon** [comment]
I'm interest to contribute react github pages here

**Comment by shakib609** [comment]
> I'm interest to contribute react github pages here

@sabbirshawon can you kindly point out the page you want to translate so that we can assign it to you?

**Comment by sabbirshawon** [comment]
> > I'm interest to contribute react github pages here
> 
> @sabbirshawon can you kindly point out the page you want to translate so that we can assign it to you?

Using the Effect Hook

**Comment by nutboltu** [comment]
@sabbirshawon `Using the Effect Hook` is assigned to you.

**Comment by sabbirshawon** [comment]
> @sabbirshawon `Using the Effect Hook` is assigned to you.

Thanks brother

**Comment by lastsaintcrucified** [comment]
@shakib609  i would like to translate the "Uncontrolled Components" in Advanced guides  please

**Comment by lastsaintcrucified** [comment]
@shakib609  i am very much interested in translating Typechecking With PropTypes page

**Comment by nutboltu** [comment]
@lastsaintcrucified I would suggest to pick any core pages first as we are almost close to release. But if you think you would start working on `Typechecking With PropTypes` then I will assign it to you.

**Comment by lastsaintcrucified** [comment]
@nutboltu Thank you very much for appreciating my request. I would like to start working on Typechecking With PropTypes . I also translated the uncontrolled component and made a pull request. Unfortunately i did not fully understand the procedeur so I translated uncontrolled component without your permission. Please accept my apology for this inconvenience. Thanks again

**Comment by nutboltu** [comment]
No worries. I assigned you in both of the pages. 🥂

**Comment by lastsaintcrucified** [comment]
@nutboltu brother you are great !! Thanks for this generosity.

**Comment by sabbirshawon** [comment]
I have faced a problem while `git push`
```
remote: Permission to reactjs/bn.reactjs.org.git denied to sabbirshawon.
fatal: unable to access 'https://github.com/reactjs/bn.reactjs.org.git/': The requested URL returned error: 403
```

**Comment by sabbirshawon** [comment]
Building Your Own Hooks

**Comment by Twaha-Rahman** [comment]
@nutboltu Sorry it took me a **while** to reply. But now that back..... I would like to translate "Virtual DOM and Internals" page. (Rest assured I am not going to run away again😅)

**Comment by nutboltu** [comment]
@Twaha-Rahman Please pick any of the core pages first, as we badly need to finish them first. :) But if you already started, then go ahead!

**Comment by Twaha-Rahman** [comment]
@nutboltu There seems to be a problem with node v12.16.1 LTS. When I cloned repo and used `yarn` to install the dependencies, it was constantly running into errors. Then this post in Stack Overflow helped me(https://stackoverflow.com/questions/58149280/fail-to-install-gatsby-starter-because-of-sharp#). After downgrading to node v10.13.0 LTS ,now everything is working fine. Just wanted to know if it was only with me or not. (Before I was using the latest node v12.16.1 LTS)

**Comment by nutboltu** [comment]
@Twaha-Rahman this repo has a node version dependency which is `lts/carbon`
https://github.com/reactjs/bn.reactjs.org/blob/5d6d4ad4b6a60c8cf81fb779a15dc29e526a7b81/.nvmrc#L1
It means we need to use `8.x` for node. It's good that it also works for `10.x`.
But it's recommended using `8.x`.

**Comment by Twaha-Rahman** [comment]
@nutboltu Sorry for the inconvenience! I have made the pull request for the translation of the page 'faq-internals'.

**Comment by Twaha-Rahman** [comment]
Am I missing something? Why has the translation process stopped? Has it been cancelled?

**Comment by nutboltu** [comment]
@Twaha-Rahman this project still is ongoing. It's an open-source project and we are all volunteers here. When we (the contributors) contribute more it will alive again :)

**Comment by Twaha-Rahman** [comment]
@nutboltu Oh, sorry.....I was worried cause I didn't see any progress for a while...

**Comment by tamzidkarim** [comment]
@nutboltu Hello. Would like to contribute to the library.
*Glossary page seems the only page from the core pages. Would you assign me to this page? 
Other pages I'm interested in:
*Building your own hooks
*Hooks api references 

Thanks.
🇧🇩
Let me know if I have to include anymore information. 
P. S. Mentioned multiple pages at the same time because saw in the list one person is assigned to multiple pages.

**Comment by nutboltu** [comment]
@tamzidkarim really appreciated! few pages are in stale mode. 
 - Rendering Elements
 - Components and Props
 - Forms
would you like to pick any of them? if not, I can assign you to the `Glossary` page

**Comment by tamzidkarim** [comment]
@nutboltu okay. Sounds fine. 
*Rendering elements
*Components and props
*Forms

**Comment by nutboltu** [comment]
@tanvirraj and @nahidmbstu I am removing your name from `Rendering elements` and `Forms` pages as these pages are assigned to you for a long time and there's no update. I hope you understand.

@tamzidkarim, I assigned you to `Rendering elements` page to get started.

**Comment by tamzidkarim** [comment]
@nutboltu Great. Thanks.

**Comment by tamzidkarim** [comment]
@nutboltu Hey could you add me to the Bengali Slack channel? Facing few errors while running it on the local machine.

**Comment by nutboltu** [comment]
@tamzidkarim could you please give me your email address?

**Comment by tamzidkarim** [comment]
e.k.tamzid@gmail.com

**Comment by Twaha-Rahman** [comment]
I've contributing to this repo for over an year and would  like to thanks everybody for their support, specially @nutboltu and @shakib609 . Really excited to see the translation of the core pages almost finished.

@nutboltu If there's any stale page, can you please assign it to me?

**Comment by nutboltu** [comment]
@Twaha-Rahman would you please take `Components and Props`?

**Comment by Twaha-Rahman** [comment]
@nutboltu How about the `Forms` and then `Components and Props`?  Cause the translation of `Forms` is so close to finished and it's stale...

**Comment by nutboltu** [comment]
@ShahadIshraq any update regarding `React` page translation? It seems the page is pretty long to translate. if you want I can help you on that.

**Comment by tamzidkarim** [comment]
@nutboltu let me know if any of the core pages is stalled or need help. If not then assign me `building your own hooks`

**Comment by nutboltu** [comment]
@tamzidkarim `Tutorial` and `Thinking in React` are still not translated. would you like to take any of them?

**Comment by sabbirshawon** [comment]
I have updated Using the Effect Hook but it still not approved yet. Have a take a look @nutboltu

**Comment by tamzidkarim** [comment]
@nutboltu okay. assign me `Tutorial`

**Comment by ShahadIshraq** [comment]
> @ShahadIshraq any update regarding `React` page translation? It seems the page is pretty long to translate. if you want I can help you on that.

Honestly, I have made very little progress and I am extremely sorry about that. Would you mind taking the lead on this? I'd appreciate if you take it up and assign a small part of it at a time to me.

**Comment by nutboltu** [comment]
@ShahadIshraq you can open a PR with the small changes you made. It's really a huge page. we can work together. for more conversation, I would request to join our slack channel.
https://rt-slack-invite.herokuapp.com

**Comment by soumiDeb** [comment]
Hi, I would like to contribute to this project. I am a native Bengali speaker. Other than that, I have working experience with react.

**Comment by shakib609** [comment]
Hello @soumiDeb. You can choose any of the un-assigned pages from the list and let us know which one you want to translate.

**Comment by soumiDeb** [comment]
Hi, @shakib609  I would like to translate **API Reference->react.component**. Assign it to me kindly.

**Comment by nutboltu** [comment]
@soumiDeb assigned to you. feel free to join our slack channel (#bn) for more collaboration
https://rt-slack-invite.herokuapp.com/

**Comment by SourangshuGhosh** [comment]
Hi, @shakib609 I would like to translate the documents into Bengali. can you please kindly assign this issue to me

**Comment by nutboltu** [comment]
@SourangshuGhosh  can you please pick any of the page from the core pages so that we can assign the page to you.

**Comment by SourangshuGhosh** [comment]
@nutboltu All the documents in the docs folder

**Comment by nutboltu** [comment]
@SourangshuGhosh Please read the issue description first. Then pick any of the pages which are not assigned to any (e.g: Thinking in React). I think it would be too much hard work for one person to translate all the pages.

Also please join the slack channel (https://rt-slack-invite.herokuapp.com/) for further discussion.

**Comment by SourangshuGhosh** [comment]
Okay @nutboltu  to start with I will take "Building Your Own Hooks"  "Hooks API Reference" and "HooksAPI"

**Comment by nutboltu** [comment]
@SourangshuGhosh  I assigned you to **Building Your Own Hooks**. Let's finish it first then we'll move to the next page.

**Comment by JubayerJoy** [comment]
Hi @nutboltu, @shakib609 I am contributing to other open sources and would love to contribute to React.
I would love to work on "Hooks API Reference" and "Hooks FAQ".
Cheers! 🚀

**Comment by shakib609** [comment]
Hello @JubayerJoy. Thank you for your interest. We are trying to finish all the core pages first. Would you be interested in translating the **Thinking in React** part of the documentation?(There's already an incomplete PR from where you can reuse some translations) If not I can assign you to the pages you mentioned.

**Comment by JubayerJoy** [comment]
@shakib609, Sure! I would love that.

**Comment by shakib609** [comment]
Thanks. Assigned to you @JubayerJoy :rocket:

**Comment by JubayerJoy** [comment]
@shakib609, I have reviewed the previous PR #47 of **Thinking in React**. The author did a lot of work but it has some issues and I think its best to start fresh.

I am working on it.
Cheers! 🚀

**Comment by oxfordhalfblood** [comment]
@nutboltu I'd love to contribute to React Bn translation. Could I translate step-2 of [**Tutorial**](bhttps://github.com/reactjs/bn.reactjs.org/blob/2c26ea9012064a2069c134934b754d2e0b9b9a53/content/tutorial/tutorial.md#setup-for-the-tutorial-setup-for-the-tutorial) page, if that's feasible? 
I see it was assigned to tamzidkarim, presumably not started yet as I can't see any PR on that yet.

**Comment by nutboltu** [comment]
@oxfordhalfblood it seems the progress of this page is in stale status. Feel free to start translating. I am going to assign you to this page as well.

**Comment by srishti666** [comment]
hi @nutboltu and @shakib609  can u assign me this issue. I want to contribute.

**Comment by shakib609** [comment]
Hello @srishti666 , please select an incomplete page from the description that you want to translate. We can assign it to you.

**Comment by nomandhoni-cs** [comment]
Hello @nutboltu I want to contribute in documentation, but this repo seems very innactive, Will you merge pull request?

**Comment by 0xriyadh** [comment]
Hey @shakib609, is the work still going on? I was wondering if I could get involved.

**Comment by gaearon** [comment]
It looks like this translation has stalled, and is now very outdated.
I'm going to archive this repo, but if someone wants to pick up, please start a new effort.
